export const questions = [
    {
        question:"1. What's your first name",
        type:"text",
        id:"firstName",
        height:"40px",
        placeholder:"Enter first name",
        bottom:"3px",
    },
    {
        question:"2. Three or four adjectives that describes you",
        type:"text",
        id:"adjectives",
        height:"130px",
        placeholder:"e.g., friendly, silly, ...",
        bottom:"6rem",
    },
    {
        question:"3. State your most important relationship",
        type:"text",
        id:"importantRelation",
        height:"130px",
        placeholder:"e.g.,daughter of ...,friend of ,....",
        bottom:"6rem",
    },
    {
        question:"4. Mention two or three things, people, or ideas that you love",
        type:"text",
        id:"loves",
        height:"130px",
        placeholder:"Enter ideas you love",
        bottom:"6rem",
    },
    {
        question:"5. Mention three feelings you have experienced",
        type:"text",
        id:"feelings",
        height:"130px",
        placeholder:"Enter feelings experienced",
        bottom:"6rem",
    },
    {
        question:"6. Mention three fears you have experienced",
        type:"text",
        id:"fears",
        height:"130px",
        placeholder:"Enter fears experienced",
        bottom:"6rem",
    },
    {
        question:"7. State your accomplishments",
        type:"text",
        id:"accomplishments",
        height:"130px",
        placeholder:"e.g., who won ..., who performed ..., who learned ...",
        bottom:"6rem",
    },
    {
        question:"8. State two or three things you want to see happen or experience",
        type:"text",
        id:"expectations",
        height:"130px",
        placeholder:"Enter your expectations",
        bottom:"6rem",
    },
    {
        question:"9. Your residence",
        type:"text",
        id:"residence",
        height:"130px",
        placeholder:"Enter your residnece",
        bottom:"6rem",
    },
    {
        question:"10. What's your last name",
        type:"text",
        id:"lastName",
        height:"130px",
        placeholder:"Enter your last name",
        bottom:"6rem",
    }

]